In [8]:
import numpy as np

# 1.创建一维数组
# array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,like=None)    
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 2. 创建多维数组
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3. 通过设置dtype参数改变数组的数据类型
c = np.array([2, 4, 6, 8], dtype="complex")
print(c)

[2.+0.j 4.+0.j 6.+0.j 8.+0.j]


In [4]:
# 4.通过 ndim 可以查看数组的维度：
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]])
print(arr.ndim)

2


In [13]:
# 5. 使用 ndmin参数创建不同维度的数组
a = np.array([1, 2, 3, 4, 5], ndmin=3)
print(a)

[[[1 2 3 4 5]]]


In [21]:
# 6. reshape函数接受一个元组作为参数，用于指定了新数组的行数和列数：
e = np.array([[1, 2], [3, 4], [5, 6]])
print("原数组:", e)
print(e.ndim)
e = e.reshape(2, 3)
print("新数组:", e)
print(e.ndim)

原数组: [[1 2]
 [3 4]
 [5 6]]
2
新数组: [[1 2 3]
 [4 5 6]]
2
