In [23]:
import numpy as np

# 1. numpy.empty()
# empty(shape, dtype=float, order='C', *, like=None)
arr = np.empty((3, 2))
print(arr)
arr = np.empty((3, 2), dtype=int)
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[3145774 5046364]
 [6553711 7078005]
 [7536741 5242880]]


In [26]:
# 2. numpy.zeros()
# zeros(shape, dtype=float, order='C', *, like=None)
a = np.zeros(6)
print(a)
b = np.zeros(6, dtype="complex64")
print(b)
# 使用自定义的数据类型
c = np.zeros((3, 3), dtype=[('x', 'i4'), ('y', 'i4')])
print(c)

[0. 0. 0. 0. 0. 0.]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[[(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]]


In [6]:
# 3. numpy.ones()
# ones(shape, dtype=None, order='C', *, like=None)
arr1 = np.ones((3, 2), dtype=int)
print(arr1)

[[1 1]
 [1 1]
 [1 1]]


In [10]:
# 4. numpy.asarray()
# asarray(a, dtype=None, order=None, *, like=None)
# 将列表转化为 numpy 数组：
l = [1, 2, 3, 4, 5, 6, 7]
a = np.asarray(l)
print(type(a))
print(a)
# 使用元组创建 numpy 数组：
l = (1, 2, 3, 4, 5, 6, 7)
a = np.asarray(l)
print(type(a))
print(a)
# 使用嵌套列表创建多维数组：
l = [[1, 2, 3, 4, 5, 6, 7], [8, 9]]
a = np.asarray(l)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
[list([1, 2, 3, 4, 5, 6, 7]) list([8, 9])]


In [11]:
# 5. numpy.frombuffer()
# frombuffer(buffer, dtype=float, count=-1, offset=0, *, like=None)
# 字节串类型
st = b'hello world'
print(type(l))
a = np.frombuffer(st, dtype="S1")
print(a)
print(type(a))

<class 'list'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


In [12]:
# 6. numpy.fromiter()
# fromiter(iterable, dtype, count=-1, *, like=None)
# 使用 range 函数创建列表对象
lis = range(6)
# 生成可迭代对象i
i = iter(lis)
# 使用i迭代器，通过fromiter方法创建ndarray
array = np.fromiter(i, dtype=float)
print(array)

[0. 1. 2. 3. 4. 5.]
