In [1]:
import numpy as np

# 1. 三角函数

arr = np.array([0, 30, 60, 90, 120, 150, 180])
# 计算arr数组中给定角度的三角函数值
# 通过乘以np.pi/180将其转换为弧度
print(np.sin(arr * np.pi / 180))
print(np.cos(arr * np.pi / 180))
print(np.tan(arr * np.pi / 180))

[0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]
[ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]
[ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [5]:
arr = np.array([0, 30, 60, 90])
# 正弦值数组
sinval = np.sin(arr * np.pi / 180)
print(sinval)
# 计算角度反正弦，返回值以弧度为单位
cosec = np.arcsin(sinval)
print(cosec)
# 通过degrees函数转化为角度进行验证
print(np.degrees(cosec))
# 余弦值数组
cosval = np.cos(arr * np.pi / 180)
print(cosval)
# 计算反余弦值，以弧度为单位
sec = np.arccos(cosval)
print(sec)
# 通过degrees函数转化为角度进行验证
print(np.degrees(sec))
# 下面是tan()正切函数
tanval = np.tan(arr * np.pi / 180)
print(tanval)
cot = np.arctan(tanval)
print(cot)
print(np.degrees(cot))

[0.        0.5       0.8660254 1.       ]
[0.         0.52359878 1.04719755 1.57079633]
[ 0. 30. 60. 90.]
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
[0.         0.52359878 1.04719755 1.57079633]
[ 0. 30. 60. 90.]
[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]
[0.         0.52359878 1.04719755 1.57079633]
[ 0. 30. 60. 90.]


In [4]:
# 2. 舍入函数

# 2.1 numpy.around()
# 该函数返回一个十进制值数，并将数值四舍五入到指定的小数位上
arr = np.array([12.202, 90.23120, 123.020, 23.202])
print(arr)
print("数组值四舍五入到小数点后两位", np.around(arr, 2))
print("数组值四舍五入到小数点后-1位", np.around(arr, -1))

[ 12.202   90.2312 123.02    23.202 ]
数组值四舍五入到小数点后两位 [ 12.2   90.23 123.02  23.2 ]
数组值四舍五入到小数点后-1位 [ 10.  90. 120.  20.]


In [3]:
# 2.2 numpy.floor()
a = np.array([-1.8, 1.1, -0.4, 0.9, 18])
# 对数组a向下取整
print(np.floor(a))

[-2.  1. -1.  0. 18.]


In [2]:
# 2.3 numpy.ceil()
a = np.array([-1.8, 1.1, -0.4, 0.9, 18])
# 对数组a向上取整
print(np.ceil(a))

[-1.  2. -0.  1. 18.]
