In [1]:
import numpy as np

# 1. numpy.arange()
# arange([start,] stop[, step,], dtype=None, *, like=None)
x = np.arange(8)
print(x)
# 设置 start 、stop 值以及步长
x = np.arange(1, 10, 2)
print(x)

[0 1 2 3 4 5 6 7]
[1 3 5 7 9]


In [2]:
# 2. numpy.linspace()
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# 表示在指定的数值区间内，返回均匀间隔的一维等差数组，默认均分 50 份
a = np.linspace(1, 10, 10)
print(a)
# endpoint 为 Fasle 时，此时不包含终止值
arr = np.linspace(10, 20, 5, endpoint=False)
print("数组数值范围 ：", arr)
# retstep参数
x = np.linspace(1, 2, 5, retstep=True)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
数组数值范围 ： [10. 12. 14. 16. 18.]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [3]:
# 3. numpy.logspace
# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
# 该函数同样返回一个 ndarray 数组，它用于创建等比数组
a = np.logspace(1.0, 2.0, num=10)
print(a)
# base = 2 的对数函数
a = np.logspace(1, 10, num=10, base=2)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
