In [18]:
import numpy as np

# 1. 基本切片
a = np.arange(10)
print(a)
# 生成切片对象
s = slice(2, 9, 3)  # 从索引2开始到索引9停止，间隔为3
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 5 8]


In [13]:
# 通过冒号来分割切片参数
a = np.arange(10)
print(a[2:9:2])

[2 4 6 8]


In [15]:
# 关于冒号的用法
a = np.arange(10)
print(a[3])
print(a[2:])
print(a[2:5])

3
[2 3 4 5 6 7 8 9]
[2 3 4]


In [24]:
# 2. 多维数组切片
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
# 从[1:]索引处开始切割
print(a[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [25]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
# # 从[:1]索引处开始切割
print(a[:1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]


In [28]:
# 省略号的使用
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
# 返回数组的第二列
print(a[..., 1])
# 返回数组的第二行
print(a[1, ...])
# 返回第二列后的所有项
print(a[..., 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
[4 5 6]
[[2 3]
 [5 6]
 [8 9]]
