In [1]:
import numpy as np

# NumPy 中的广播机制（Broadcast）旨在解决不同形状数组之间的算术运算问题。
# 我们知道，如果进行运算的两个数组形状完全相同，它们直接可以做相应的运算
a = np.array([0.1, 0.2, 0.3, 0.4])
b = np.array([10, 20, 30, 40])
c = a * b
print(c)

[ 1.  4.  9. 16.]


In [2]:
# NumPy 设计了一种广播机制，这种机制的核心是对形状较小的数组，在横向或纵向上进行一定次数的重复，使其与形状较大的数组拥有相同的维度
a = np.array(
    [[0, 0, 0],
     [10, 10, 10],
     [20, 20, 20],
     [30, 30, 30]]
)
# b数组与a数组形状不同
b = np.array([1, 2, 3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [3]:
a = np.array(
    [[0, 0, 0],
     [10, 10, 10],
     [20, 20, 20],
     [30, 30, 30]]
)
b = np.array([[1, 2, 3],[4, 5 ,6]])
print(a + b)

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 