In [15]:
import numpy as np

a = np.arange(0, 60, 5).reshape(3, 4)
print(a)
# 使用nditer迭代器,并使用for进行遍历
for x in np.nditer(a):
    print(x, end=", ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [16]:
a = np.arange(0, 60, 5).reshape(3, 4)
print(a)
# a的转置数组
b = a.T
print(b)
for x in np.nditer(b):
    print(x, end=", ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [17]:
a = np.arange(0, 60, 5).reshape(3, 4)
print(a)
# copy方法生成数组副本
for x in np.nditer(a.T.copy(order='C')):
    print(x, end=", ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

In [18]:
a = np.arange(0, 60, 5).reshape(3, 4)
print(a)
# copy方法生成数组副本
for x in np.nditer(a.T.copy(order='F')):
    print(x, end=", ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [11]:
a = np.arange(0, 60, 5).reshape(3, 4)
print("原数组是:", a)
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = 2 * x
print('修改后的数组是：', a)

原数组是: [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
修改后的数组是： [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [12]:
a = np.arange(0, 60, 5).reshape(3, 4)
print("原数组", a)
# 修改后数组
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print(x)

原数组 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In [14]:
a = np.arange(0, 60, 5).reshape(3, 4)
print(a)
b = np.array([1, 2, 3, 4], dtype=int)
print(b)
# 广播迭代
for x, y in np.nditer([a, b]):
    print("%d:%d" % (x, y), end=", ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[1 2 3 4]
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 