In [10]:
import numpy as np

# 1. numpy.resize()
# numpy.resize() 返回指定形状的新数组。
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
# a数组的形状
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
b = np.resize(a, (3, 2))
# b数组
print(b)
# b数组的形状
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [12]:
# 修改c数组使其形状大于原始数组
c = np.resize(a, (3, 3))
print(c)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [6]:
# 2. numpy.append()
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
# 向数组a添加元素
print(np.append(a, [7, 8, 9]))

[1 2 3 4 5 6 7 8 9]


In [8]:
# 沿轴 0 添加元素
print(np.append(a, [[7, 8, 9]], axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# 沿轴 1 添加元素
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [16]:
# 3. numpy.insert()
# 表示沿指定的轴，在给定索引值的前一个位置插入相应的值，如果没有提供轴，则输入数组被展开为一维数组
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
# 不提供axis的情况，会将数组展开
print(np.insert(a, 3, [11, 12]))

[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3 11 12  4  5  6]


In [14]:
# 沿轴 0 垂直方向
print(np.insert(a, 1, [11], axis=0))

[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


In [15]:
# 沿轴 1 水平方向
print(np.insert(a, 1, 11, axis=1))

[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [17]:
# 4. numpy.delete()
a = np.arange(12).reshape(3, 4)
# a数组
print(a)
# 不提供axis参数情况
print(np.delete(a, 5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]


In [18]:
# 删除第二列
print(np.delete(a, 1, axis=1))

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [19]:
# 删除经切片后的数组
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.delete(a, np.s_[::2]))

[ 2  4  6  8 10]


In [20]:
# 5. numpy.argwhere()
x = np.arange(6).reshape(2, 3)
print(x)

[[0 1 2]
 [3 4 5]]


In [21]:
# 返回所有大于1的元素索引
y = np.argwhere(x > 1)
print(y)

[[0 2]
 [1 0]
 [1 1]
 [1 2]]


In [22]:
# 6. numpy.unique()
a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])
print(a)

[5 2 6 2 7 5 6 8 2 9]


In [23]:
# 对a数组的去重
uq = np.unique(a)
print(uq)

[2 5 6 7 8 9]


In [26]:
# 数组去重后的索引数组
u, indices = np.unique(a, return_index=True)
# 数组去重
print(u)
# 打印去重后数组的索引
print(indices)

[2 5 6 7 8 9]
[1 0 2 4 7 9]


In [27]:
# 去重数组的下标：
ui, indices = np.unique(a, return_inverse=True)
print(ui)
# 打印下标
print(indices)

[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


In [28]:
# 返回去重元素的重复数量
uc, indices = np.unique(a, return_counts=True)
print(uc)

[2 5 6 7 8 9]


In [29]:
# 元素出现次数：
print(indices)

[3 2 2 1 1 1]
